# Copyright 2024 Google LLC
# SPDX-License-Identifier: Apache-2.0

name: Setup Zephyr project
description: Setup a Zephyr base project using west and downloading the Zephyr SDK

inputs:
  app-path:
    description: |
      Application code path, should contain a west.yml file if
      "manifest-file-name" is not specified, cannot contain multiple
      directories (use base-path instead)
    required: true

  base-path:
    description: |
      Application base path, should contain the app-path. Defaults to "." if
      unspecified
    required: false
    default: .

  ccache-max-size:
    description: |
      Maximum size of the files stored in the compiler cache (ccache). Defaults to 512MB.
    required: false
    default: 512MB

  enable-ccache:
    description: |
      Enable caching/restoring of compiler cache (ccache) files between invocations.
      Defaults to 'true'.
    required: false
    default: true

  ccache-cache-key:
    description: |
      An additional string used in the ccache cache key, use it to identify the
      cache in a way that makes sense for compiled object cache reuse between
      different build workflows. Default to "default".
    required: false
    default: default

  manifest-file-name:
    description: Name of the west workspace manifest file name in "app-path"
    required: false
    default: west.yml

  sdk-version:
    description: Zephyr SDK version to use or "auto" to detect automatically
    required: false
    default: auto

  sdk-base:
    description: Base URL of the Zephyr SDK
    required: false
    default: https://github.com/zephyrproject-rtos/sdk-ng/releases/download

  toolchains:
    description: List of toolchains to install, colon separated
    required: false
    default: arm-zephyr-eabi

  west-project-filter:
    description: West project filter
    required: false
    default: ""

  west-group-filter:
    description: West group filter
    required: false
    default: ""

  west-version:
    description: West version to install, latest if omitted
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ runner.os }}" = "Windows" ]; then
          python.exe -m pip install -U pip
        fi

        pip3 install -U pip wheel

        if [ -n "${{ inputs.west-version }}" ]; then
          pip3 install west==${{ inputs.west-version }}
        else
          pip3 install west
        fi

        if [ "${{ runner.os }}" = "Linux" ]; then
          sudo rm -f /var/lib/man-db/auto-update
          sudo apt-get update -y
          sudo apt-get install -y ninja-build ccache gperf
          if [ "${{ runner.arch }}" = "X64" ]; then
            sudo apt-get install -y libc6-dev-i386 g++-multilib
          fi
        elif [ "${{ runner.os }}" = "macOS" ]; then
          brew install ninja ccache qemu dtc gperf
        elif [ "${{ runner.os }}" = "Windows" ]; then
          choco feature enable -n allowGlobalConfirmation
          choco install ninja wget gperf
        fi

    - name: Initialize
      working-directory: ${{ inputs.base-path }}
      shell: bash
      run: |
        set -vx
        python3 -m venv ~/zephyrproject/.venv
        source ~/zephyrproject/.venv/bin/activate
        west init ~/zephyrproject
        cd ~/zephyrproject
        west update -o=--depth=1 -n  
        west zephyr-export
        west packages pip --install --ignore-venv-check
        cd zephyr
        west sdk install

        #cd ${{ inputs.base-path }}/platforms/Zephyr
        #source /zephyrproject/.venv/bin/activate
        #source ${{ inputs.base-path }}/zephyrproject/zephyr/zephyr-env.sh
        #todo build wasm binary
        west build -b esp32_devkitc_wroom/esp32/procpu
    - name: Build project
      working-directory: ${{ inputs.base-path }}
      id: env-setup
      shell: bash
      run: |
        #cd WARduino/platforms/Zephyr
        cd platforms/Zephyr
        source ~/zephyrproject/.venv/bin/activate
        source ~/zephyrproject/zephyr/zephyr-env.sh
        #todo build wasm binary
        west build -b esp32_devkitc_wroom/esp32/procpu
